[libraries]
immutables-value = { module = "org.immutables:value", version = "2.5.6" }
junit = { module = "junit:junit", version = "4.12" }

[plugins]
release = { id = "pl.allegro.tech.build.axion-release", version = "1.18.8" }
