[libraries]
immutables-value = { module = "org.immutables:value", version = "2.10.1" }
junit = { module = "junit:junit", version = "4.12" }

[plugins]
nexus = {id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0"}
release = { id = "pl.allegro.tech.build.axion-release", version = "1.19.1" }
